-- 1. Create the contacts table if it doesn't already exist
create table if not exists public.contacts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    first_name text,
    last_name text,
    email text,
    phone text,
    message text
);

-- 2. Enable row level security (RLS) to protect it from unauthorized access
alter table public.contacts enable row level security;

-- 3. Create policies
-- We allow insertion from the front-end
create policy "Enable insert for everyone" 
on public.contacts for insert with check (true);

-- We allow selection for the admin dashboard (ensure you protect the page with proper auth later)
create policy "Enable read for everyone" 
on public.contacts for select using (true);

